# Generated by Django 5.0.6 on 2024-06-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=40)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNoticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Noticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulonoticia', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=40)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodista')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiponoticas')),
            ],
        ),
    ]
